// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoFinal.Data.Models;

#nullable disable

namespace ProjetoFinal.Migrations
{
    [DbContext(typeof(ProjectContext))]
    [Migration("20240208131342_ExcludingChampionshipTable")]
    partial class ExcludingChampionshipTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ProjetoFinal.Data.Models.Characters", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CharacterID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Age")
                        .HasColumnType("int")
                        .HasColumnName("CharacterAGE");

                    b.Property<int>("Defeat")
                        .HasColumnType("int")
                        .HasColumnName("DefeatFIGHTS");

                    b.Property<int>("Fights")
                        .HasColumnType("int")
                        .HasColumnName("TotalFIGHTS");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("CharacterNAME");

                    b.Property<int>("Power")
                        .HasColumnType("int")
                        .HasColumnName("Power");

                    b.Property<int>("Victory")
                        .HasColumnType("int")
                        .HasColumnName("VictoryFIGHTS");

                    b.HasKey("Id");

                    b.ToTable("Tabela_de_Personagens");
                });
#pragma warning restore 612, 618
        }
    }
}
